### Evaluation Metrics in Machine Learning

Evaluation metrics are essential in assessing the performance of a machine learning model. They help in understanding how well a model makes predictions and in identifying areas for improvement. The choice of metric can depend on the type of problem (classification, regression, etc.) and the specific goals of the application.

#### 1. Classification Metrics

- **Accuracy**: The ratio of correctly predicted instances to the total instances.
  
  $$
  \text{Accuracy} = \frac{\text{Number of Correct Predictions}}{\text{Total Number of Predictions}}
  $$

- **Precision**: The ratio of correctly predicted positive observations to the total predicted positives.
  
  $$
  \text{Precision} = \frac{TP}{TP + FP}
  $$
  
- **Recall (Sensitivity)**: The ratio of correctly predicted positive observations to all observations in the actual class.
  
  $$
  \text{Recall} = \frac{TP}{TP + FN}
  $$
  
- **F1 Score**: The harmonic mean of precision and recall.
  
  $$
  F1 = 2 \cdot \frac{\text{Precision} \cdot \text{Recall}}{\text{Precision} + \text{Recall}}
  $$

- **Confusion Matrix**: A table used to describe the performance of a classification model.

Confusion Matrix Layout:

<table>
    <tr>
        <th>Actual \ Predicted</th>
        <th>Negative</th>
        <th>Positive</th>
    </tr>
    <tr>
        <td>Negative</td>
        <td>TN</td>
        <td>FP</td>
    </tr>
    <tr>
        <td>Positive</td>
        <td>FN</td>
        <td>TP</td>
    </tr>
</table>









- **ROC-AUC (Receiver Operating Characteristic - Area Under Curve)**: A plot of true positive rate (recall) against the false positive rate. AUC measures the entire two-dimensional area underneath the entire ROC curve.

#### 2. Regression Metrics

- **Mean Absolute Error (MAE)**: The average of the absolute errors between predicted and actual values.

$$
MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y_i}|
$$

- **Mean Squared Error (MSE)**: The average of the squared errors between predicted and actual values.

$$
MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y_i})^2
$$

- **Root Mean Squared Error (RMSE)**: The square root of the average of squared errors.

$$
RMSE = \sqrt{MSE}
$$

- **R-Squared (R²)**: The proportion of the variance in the dependent variable that is predictable from the independent variables.

$$
R^2 = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y_i})^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2}
$$


### Coding Exercises

#### Exercise 1: Classification Metrics

1. Load a classification dataset (e.g., Iris dataset).
2. Split the dataset into training and testing sets.
3. Train a classification model (e.g., Decision Tree).
4. Calculate and print the accuracy, precision, recall, F1 score, and confusion matrix.

In [3]:
# Classification Example with Iris Dataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.preprocessing import label_binarize

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)

# For ROC-AUC (multi-class)
y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
y_pred_bin = label_binarize(y_pred, classes=[0, 1, 2])
roc_auc = roc_auc_score(y_test_bin, y_pred_bin, average='weighted', multi_class='ovr')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"ROC-AUC: {roc_auc}")


Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
ROC-AUC: 1.0


#### Exercise 2: Regression Metrics

1. Load a regression dataset (e.g., Boston housing dataset).
2. Split the dataset into training and testing sets.
3. Train a regression model (e.g., Linear Regression).
4. Calculate and print MAE, MSE, RMSE, and R².


In [5]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Load dataset
california = fetch_california_housing()
X = california.data
y = california.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a model
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-Squared (R²): {r2}")


Mean Absolute Error (MAE): 0.5272474538306174
Mean Squared Error (MSE): 0.5305677824766757
Root Mean Squared Error (RMSE): 0.7284008391515455
R-Squared (R²): 0.595770232606166


### Tips for Using These Metrics

1. **Accuracy**: Best for balanced datasets where all classes are equally important.
2. **Precision and Recall**: Crucial when you have imbalanced datasets or when the cost of false positives and false negatives is high.
3. **F1 Score**: Useful when you need a balance between precision and recall.
4. **Confusion Matrix**: Helps understand the model's performance across different classes.
5. **ROC-AUC**: Good for binary classification tasks and provides a single metric that summarizes the performance.
6. **MAE, MSE, RMSE**: Commonly used in regression tasks. MAE is less sensitive to outliers compared to MSE and RMSE.
7. **R-Squared**: Indicates the goodness of fit of the model. However, be cautious as it does not account for overfitting.

By carefully selecting the appropriate evaluation metrics based on the type of problem and dataset characteristics, you can get a more comprehensive understanding of your model's performance.


### Common Datasets and Suitable Evaluation Metrics

1. **Breast Cancer Dataset**
   - **Description**: This dataset is used for binary classification. It contains features extracted from breast cancer biopsies to predict whether the cancer is malignant or benign.
   - **Metrics**:
     - **Accuracy**: Measures the proportion of correct predictions.
     - **Precision**: Useful if false positives are costly (e.g., predicting benign as malignant).
     - **Recall**: Useful if false negatives are costly (e.g., missing a malignant case).
     - **F1 Score**: Balances precision and recall.
     - **Confusion Matrix**: Provides detailed insights into TP, TN, FP, and FN.
     - **ROC-AUC**: Evaluates the performance of the classification model across different thresholds.



In [6]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.preprocessing import label_binarize

# Load dataset
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a model
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"ROC-AUC: {roc_auc}")


Accuracy: 0.9766081871345029
Precision: 0.9814814814814815
Recall: 0.9814814814814815
F1 Score: 0.9814814814814815
Confusion Matrix:
[[ 61   2]
 [  2 106]]
ROC-AUC: 0.9748677248677248


2. **Credit Card Fraud Detection**
   - **Description**: This dataset is used for anomaly detection or binary classification to identify fraudulent transactions.
   - **Metrics**:
     - **Accuracy**: May be misleading if fraud cases are rare.
     - **Precision**: Important as fraud cases are usually rare.
     - **Recall**: Important to detect as many fraud cases as possible.
     - **F1 Score**: Balances precision and recall.
     - **Confusion Matrix**: Helps in understanding the performance for fraudulent vs. non-fraudulent transactions.
     - **ROC-AUC**: Measures the model's ability to distinguish between fraudulent and non-fraudulent transactions.


In [7]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score

# Load dataset
fraud = fetch_openml('credit-card-fraud')
X = fraud.data
y = fraud.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a model
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"ROC-AUC: {roc_auc}")


OpenMLError: No active dataset credit-card-fraud found.


3. **Diabetes Dataset**
   - **Description**: Used for regression tasks to predict diabetes progression based on various features.
   - **Metrics**:
     - **Mean Absolute Error (MAE)**: Measures the average magnitude of errors in predictions.
     - **Mean Squared Error (MSE)**: Penalizes larger errors more severely than MAE.
     - **Root Mean Squared Error (RMSE)**: Provides the error magnitude in the same units as the target variable.
     - **R-Squared (R²)**: Indicates how well the model explains the variance in the target variable.

In [8]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Load dataset
diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a model
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-Squared (R²): {r2}")


Mean Absolute Error (MAE): 41.91937845679274
Mean Squared Error (MSE): 2821.750981001311
Root Mean Squared Error (RMSE): 53.120156070942706
R-Squared (R²): 0.4772897164322617
